module.exports = {
  C2S: {
    JOIN: "JOIN",
    BUZZ: "BUZZ",
    BUZZER_OPEN: "BUZZER_OPEN",
    BUZZER_RESET: "BUZZER_RESET",

    JUDGE_CORRECT: "JUDGE_CORRECT",
    JUDGE_WRONG: "JUDGE_WRONG",
    JUDGE_SKIP: "JUDGE_SKIP",
    NEXT_QUESTION: "NEXT_QUESTION",
    SET_QUESTION_NO: "SET_QUESTION_NO",
    CHANGE_NAME: "CHANGE_NAME",
    SET_PLAYER_ORDER: "SET_PLAYER_ORDER",

    SET_THINKING_SECONDS: "SET_THINKING_SECONDS",
    SET_REST_PENALTY: "SET_REST_PENALTY",
    PLAY_SFX: "PLAY_SFX",
    EXPORT_RULE_PRESET: "EXPORT_RULE_PRESET",
    LIST_RULE_PRESETS: "LIST_RULE_PRESETS",
    APPLY_RULE_PRESET: "APPLY_RULE_PRESET",
    RESET_CONTROLLER_PREFS: "RESET_CONTROLLER_PREFS",

    SET_ACTIVE_MOD: "SET_ACTIVE_MOD"
  },
  S2C: {
    HELLO: "HELLO",
    SELF: "SELF",
    STATE: "STATE",
    ERROR: "ERROR",
    RELOAD: "RELOAD"
  }
};
